name: check

on:
  # push:
  workflow_dispatch:
  # schedule:
  # - cron: '0 0,4 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: python 3.10
        uses: actions/setup-python@master
        with:
          python-version: '3.10'
      - name: Env
        run: pip install -r requirements.txt
      - name: check
        run: python check.py
      - name: Commit
        run: |
          git config --local user.email "goonhope@gmail.com"
          git config --local user.name "goonhope"
          git add -A
          git commit -m "Update `date -d '8 hour' '+%Y/%m/%d %H:%M:%S'`" -a
      - name: Push back
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN }}
          branch: main 
